[model]
[model.shared]
latent_size = 32
transformation_dimension_size = 10
[model.encoder]
grid_size = 900
hidden_sizes = [1024, 4]
attention_sizes = [10,10,10]
learning_rate = 0.001
alpha = 0.80
tau = 0.85
[model.transformer]
learning_rate = 0.001
alpha = 0.9
[model.encoder.downstream_attributes]
grid_size = {hidden_size = 10, output_size = 2, output_channels=30}
num_colors = {hidden_size = 10, output_size = 1, output_channels=10}
[model.encoder.contrastive_attributes]
roll = {task_type = "task_sensitive", activation = "sigmoid"}
scale_grid = {task_type = "task_sensitive", activation = "sigmoid"}
isolate_color = {task_type = "task_sensitive", activation = "sigmoid"}

[training]
[training.shared]
dataset_path = "training"
[training.encoder]
batch_size = 10
epochs = 2
[training.transformer]
batch_size = 1
epochs = 1